#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="$ROOT_DIR/target/pitch_demo"
HARNESS_STATE="$TARGET_DIR/harness_state.json"

mkdir -p "$TARGET_DIR"
rm -f "$TARGET_DIR"/*.jsonl "$TARGET_DIR"/*.csv "$TARGET_DIR"/*.json "$TARGET_DIR"/*.md

echo "[pitch] Preparing stimulus schedule for high-threat scenario..."
STIMULUS_FILE="$TARGET_DIR/intense_stimulus.jsonl"
cargo run --quiet --bin stimulus -- "$STIMULUS_FILE" activator 0.9 4
cargo run --quiet --bin stimulus -- "$STIMULUS_FILE" inhibitor 0.45 6

run_scenario() {
  local label="$1"
  local scenario_path="$2"
  local use_stimulus="$3"
  local telemetry_file="$TARGET_DIR/${label}_telemetry.jsonl"
  local metrics_csv="$TARGET_DIR/${label}_step_metrics.csv"
  local vega_spec="$TARGET_DIR/${label}_vega.json"
  local harness_json="$TARGET_DIR/${label}_outcome.json"

  echo "[pitch] Running scenario '$label' ($scenario_path)..."
  if [[ "$use_stimulus" == "true" ]]; then
    cargo run --quiet --bin morphogenetic-security -- \
      --config "$scenario_path" \
      --telemetry "$telemetry_file" \
      --stimulus "$STIMULUS_FILE"
  else
    cargo run --quiet --bin morphogenetic-security -- \
      --config "$scenario_path" \
      --telemetry "$telemetry_file"
  fi

  echo "[pitch] Summarising telemetry for '$label'..."
  python3 "$ROOT_DIR/scripts/analyze_telemetry.py" "$telemetry_file" --limit 25 > "$TARGET_DIR/${label}_analysis.txt"
  local prepare_args=(
    python3 "$ROOT_DIR/scripts/prepare_telemetry_dashboard.py" "$telemetry_file"
    --output "$metrics_csv"
    --vega-lite "$vega_spec"
    --lineage-output "$TARGET_DIR/${label}_lineage.csv"
  )
  if [[ "$use_stimulus" == "true" ]]; then
    prepare_args+=(--stimulus "$STIMULUS_FILE")
  fi
  "${prepare_args[@]}"

  echo "[pitch] Scoring adversarial pressure for '$label'..."
  local emit_args=(
    cargo run --quiet --bin adversarial_cycle --
    --candidate-id "pitch-${label}"
    --scenario "$scenario_path"
    --generation 0
    --metrics "$metrics_csv"
    --state "$HARNESS_STATE"
    --emit-json "$harness_json"
  )
  if [[ "$use_stimulus" == "true" ]]; then
    emit_args+=(--stimulus "$STIMULUS_FILE")
  fi
  "${emit_args[@]}"
}

run_scenario "baseline" "$ROOT_DIR/docs/examples/baseline-growth.yaml" "false"
run_scenario "intense" "$ROOT_DIR/docs/examples/intense-defense.yaml" "true"

cat <<'EOF' > "$TARGET_DIR/pitch_cheatsheet.md"
# Pitch Prototype Cheatsheet

Artifacts generated by `scripts/pitch_demo.sh`:

- `baseline_analysis.txt` — quick textual telemetry summary for the calm baseline run.
- `intense_analysis.txt` — contrasting summary for the adversarial run with stimuli.
- `baseline_step_metrics.csv` / `intense_step_metrics.csv` — per-step metrics for charts.
- `baseline_lineage.csv` / `intense_lineage.csv` — lineage trajectories in long format.
- `baseline_vega.json` / `intense_vega.json` — Vega-Lite specs ready for observable notebooks.
- `baseline_outcome.json` / `intense_outcome.json` — adversarial harness scoring payloads.
- `harness_state.json` — persisted harness backlog showing queued follow-ups post demo.

Suggested live narrative:
1. Show baseline telemetry summary → highlight stable threat and replication metrics.
2. Contrast with intense run summary → point to spike in threat, stimuli totals, and fitness.
3. Open `intense_outcome.json` → note recommended mutation and backlog growth.
4. Load `intense_vega.json` in a Vega viewer → visualise threat vs. replication over time.

EOF

echo "[pitch] Prototype assets ready under $TARGET_DIR"
